export const COLORS = {
  primary: "#006B3F", // Verde institucional
  secondary: "#F7C600", // Amarelo institucional
  accent: "#1E4D8C", // Azul institucional
  background: "#F8FAFC",
  card: "#FFFFFF",
  border: "#E5E7EB",
  text: "#1F2937",
  muted: "#6B7280",
};

// Estrutura de dados com múltiplos cursos e seus respectivos dados
export const COURSES_DATA = [
  {
    id: "curso-1",
    nome: "Técnico em Secretaria Escolar",
    turmas: ["Turma 2026.1"],
    periodos: ["2026.1"],
    componentes: [""],
    professores: ["Prof. Italo Diego"],
    polos: ["Rio Branco"],
    alunos: [
      "Ayrton Ronald Figueiredo de Araújo",
      "Carlos da Silva Sarkis",
      "Cleyson André Rodrigues Maia",
      "Dyenne Késsia Opes Sousa",
      "Edilaide da Silva Felismino",
      "Elisângela Guimarães de Menezes Felix",
      "Elza Rocha de Menezes",
      "Emilly de Oliveira Araújo",
      "Fernanda Silva Mota",
      "Francilane de Souza Tuesta",
      "Francisca Aparecida da Silva Paiva",
      "Jeane Maria Oliveira Vilaço",
      "Jeronimo de Lima Paz",
      "João Augusto Monteiro Maia",
      "Joceli Moura do Nascimento Loureiro",
      "Jose Felix Alves de Brito",
      "Juliana Sombra Aguiar",
      "Kamilly Cavalcante Silva",
      "Karen Souza Melo Nunes",
      "Louhan Elias Melo Almeida",
      "Luena da Silva Melo",
      "Manuella Maria da Silva Vale",
      "Marilene Nunes Gomes",
      "Marlene da Silva Rodrigues",
      "Marlene Fernandes de Oliveira",
      "Marleude Cabral Marques",
      "Paulo Fernando da Silva Pessoa",
      "Raimunda Carneiro da Silva",
      "Rosiane Silva dos Santos",
      "Sonia Maria Nogueira da Silva",
      "Stallin Naubert Silva de Araújo",
      "Sueli da Silva Monteiro",
      "Suely Moura Nascimento Costa",
      "Thainara Lima da Silva",
      "Wemerson dos Santos Dias",
    ],
  },
  {
    id: "curso-2",
    nome: "Técnico em Multimeios Didáticos",
    turmas: ["Turma 2026.1"],
    periodos: ["2026.1"],
    componentes: [""],
    professores: ["Prof. Antônio Júnior"],
    polos: ["Rio Branco"],
    alunos: [
      "Andreza dos Santos Zailo",
      "Antonia Isabel Mourão Rodrigues",
      "Antonio Raidson Ferreira da Silva",
      "Cleonice Santos de Souza",
      "Cristiane Nascimento da Silva",
      "Edilene Losano Geraldo",
      "Eliana Sabrina de Souza Barbosa",
      "Eliton Lopes Oliveira",
      "Fabiana Lopes Miranda",
      "Gleyson Souza do Nascimento",
      "Iolanda Ricardo de Lima",
      "Jaqueline Marina de Castro Cordeiro",
      "Alines Daniel do Nascimento Lopes",
      "Jéssica da Silva Araújo",
      "Jonas Castro de Lucena",
      "Jorteline Andrade de Freitas",
      "Lourdes Silva do Nascimento Barbosa",
      "Luciele Sobralino Cordeiro",
      "Márcio Paulo Matos de Lima",
      "Maria Jose Silva Murici",
      "Romária Pessoa da Silva",
      "Raimunda Cerqueira dos Santos",
      "Rosana Guilherme da Silva",
      "Samia Cristina Rafael da Costa",
      "Silmara Veloso Ortega",
      "Sueli Duarte Bezerra",
      "Suiane Veríssimo da Silva",
      "Ueverson Mota Ferreira Abud",
      "Veida Oliveira Silva",
      "Wederson Correia Saraiva",
    ],
  },
  {
    id: "curso-3",
    nome: "Técnico em Alimentação Escolar - RB",
    turmas: ["Turma 2026.1"],
    periodos: ["2026.1"],
    componentes: [""],
    professores: ["Prof. Sergiane"],
    polos: ["Rio Branco"],
    alunos: [
      "Antônia Cunha Figueiredo da Silva",
      "Antonia Muniz da Silva",
      "Antonia Pereira de Sousa",
      "Auxiliadora Celestino de Souza",
      "Camila Gomes de Souza",
      "Cristiana Costa da Rocha",
      "Edclecia da Silva Freitas",
      "Edina Pereira de Souza",
      "Eduardo Oliveira dos Santos",
      "Elisania Dossimo Ferreira",
      "Jaqueline Batista da Costa",
      "Luana Ferreiraa Majacundi Castelo",
      "Luck Vanbeli Aguiar de Araújo",
      "Maria Dionisia Lucas do Nascimento",
      "Maria Leuda Vieira Barbosa Silva",
      "Maria Lucileide da Silva Marinho",
      "Maria Luiza Gomes de Souza",
      "Maria Luiza Melo de Souza",
      "Maria Silva de Souza dos Santos",
      "Marineide Vale Brandão Alves",
      "Marli de Oliveira Ribeiro Sousa",
      "Maria Francisca Marcelino de Lima Fortunato",
      "Poliana Teixeira Gomes",
      "Quezia de Oliveira Silva Melo",
      "Rafaela Barros Freitas da Silva",
      "Samia de Brito Queiroz",
      "Valéria da Silva Pereira",
      "Vanessa Raiane Rodrigues de Araújo",
      "Willy Nascimento de Souza",
      "Betania Venancio Moraes",
    ],
  },
  {
    id: "curso-4",
    nome: "Técnico em Alimentação Escolar - CZS",
    turmas: ["Turma 2026.1"],
    periodos: ["2026.1"],
    componentes: [""],
    professores: [""],
    polos: ["Cruzeiro do Sul"],
    alunos: [],
  },
  {
    id: "curso-5",
    nome: "Técnico em Infraestrutura",
    turmas: ["Turma 2026.1"],
    periodos: ["2026.1"],
    componentes: [""],
    professores: [""],
    polos: ["Cruzeiro do Sul"],
    alunos: [],
  },
];

// Dados padrão para inicialização
export const DEFAULT_COURSE = COURSES_DATA[0];

export const COURSE_INFO = {
  curso: DEFAULT_COURSE.nome,
  turma: DEFAULT_COURSE.turmas[0],
  componenteCurricular: DEFAULT_COURSE.componentes[0],
  periodo: DEFAULT_COURSE.periodos[0],
  cargaHoraria: "120h",
  professorFormador: DEFAULT_COURSE.professores[0],
  mediadorPresencial: "Nome do Mediador",
  poloMunicipio: DEFAULT_COURSE.polos[0],
};

export const STUDENTS = DEFAULT_COURSE.alunos;
